[browser]
gatherUsageStats = false

[global]
showWarningOnDirectExecution = false

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 1024  # MB
maxMessageSize = 1024  # MB

[theme]
base = "light"
primaryColor = "#2B6CB0"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7FAFC"
textColor = "#1A202C"
font = "sans serif"